public class DemoClass2 {
public static void DemoMethod(){
    // public static void MymethodName(){}
    String word = 'Life is beautiful';
    string ConcatenationNew = word+word;
  // dataType Variable
    
    integer Numbers = 1023;
        integer Numbers2 = 989;

    integer additionOfTwoNumber = Numbers2*Numbers;
    integer calculatedValue = 2*additionOfTwoNumber;
    
        System.debug(additionOfTwoNumber);
            System.debug('additionOfTwoNumber >>>>>'+additionOfTwoNumber);
            System.debug('calculatedValue >>>>>'+calculatedValue);

            

    }
}