@isTest
private class Emptest{
    @isTest
    private static void oppCreateMethod(){
        
          /*  Opportunity opp = new Opportunity();
            opp.CloseDate=Date.Today();
            opp.StageName='CLosed Won';
            opp.Name='JOB1';
        insert opp;
        oppclass.oppmethod();
        Opportunity oppNew =[select id,name from opportunity where id =:opp.Id Limit 1];
         system.assertEquals(oppNew.name,opp.name);*/
    }

}