public class Students {
public integer testNum;
public string testName;
    //  we need to add the value of the anove
    //  properties object by object 
    //  we need one word to access every objects
 
   Public Students (){
        this.testNum = 90;
        this.testName = 'Testing Constructor 33434';
    }   
    // construtor Overloading
       Public Students (Integer testNum, String testName){
        this.testNum = testNum;
        this.testName = testName;
    }
}